pub mod ffi;

use rqtk_core::RequirementSet;
use std::collections::BTreeSet;
use std::path::Path;

pub fn collect_verification_activity_ids_from_repo_root(
    repo_root: &Path,
) -> Result<Vec<String>, String> {
    let set = RequirementSet::load_from_repo_root(repo_root).map_err(|e| {
        format!(
            "cannot load requirements from `{}`: {e}",
            repo_root.display()
        )
    })?;

    let mut acc = BTreeSet::<String>::new();
    for req in set.requirements.values() {
        for activity in &req.requirement.verification.activities {
            if !activity.id.trim().is_empty() {
                acc.insert(activity.id.clone());
            }
        }
    }
    Ok(acc.into_iter().collect())
}

pub fn render_header(activity_ids: &[String], repo_root: &Path, macro_name: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by rqtk-cpp\n");
    out.push_str(&format!("// Source repo root: {}\n", repo_root.display()));
    out.push_str("#pragma once\n\n");
    out.push_str("#include <array>\n");
    out.push_str("#include <string_view>\n\n");
    out.push_str("namespace rqtk {\n");
    out.push_str("namespace verification {\n\n");
    out.push_str(&format!(
        "inline constexpr std::array<std::string_view, {}> kActivityIds = {{\n",
        activity_ids.len()
    ));
    for activity_id in activity_ids {
        out.push_str(&format!("    \"{}\",\n", escape_cxx_string(activity_id)));
    }
    out.push_str("};\n\n");
    out.push_str(
        "constexpr bool is_valid_verification_id(std::string_view candidate) noexcept {\n",
    );
    out.push_str("    for (const auto known : kActivityIds) {\n");
    out.push_str("        if (known == candidate) {\n");
    out.push_str("            return true;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return false;\n");
    out.push_str("}\n\n");
    out.push_str("}  // namespace verification\n");
    out.push_str("}  // namespace rqtk\n\n");
    out.push_str(&format!(
        "#define {}(ACTIVITY_ID_LITERAL)                                \\\n",
        macro_name
    ));
    out.push_str("    static_assert(                                                         \\\n");
    out.push_str(
        "        ::rqtk::verification::is_valid_verification_id(ACTIVITY_ID_LITERAL), \\\n",
    );
    out.push_str(&format!(
        "        \"Unknown verification activity ID in {}(...)\")\n",
        macro_name
    ));
    out
}

pub fn generate_header_file(
    repo_root: &Path,
    output: &Path,
    macro_name: &str,
) -> Result<usize, String> {
    let ids = collect_verification_activity_ids_from_repo_root(repo_root)?;
    let rendered = render_header(&ids, repo_root, macro_name);

    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create directory `{}`: {}", parent.display(), e))?;
    }
    std::fs::write(output, rendered)
        .map_err(|e| format!("cannot write `{}`: {}", output.display(), e))?;
    Ok(ids.len())
}

fn escape_cxx_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_contains_macro_and_ids() {
        let ids = vec!["VA-A".to_owned(), "VA-B".to_owned()];
        let rendered = render_header(&ids, Path::new("."), "VERIFIES");
        assert!(rendered.contains("kActivityIds"));
        assert!(rendered.contains("\"VA-A\""));
        assert!(rendered.contains("\"VA-B\""));
        assert!(rendered.contains("VERIFIES"));
    }
}
