#!/usr/bin/env python3
"""Build rqtk.dev into site/dist/.

1. Generate the reference pages from the rqtk binary itself (command help, lint rules, file
   format schemas), so the docs cannot drift from the tool.
2. Build the mdBook docs into dist/docs/.
3. Copy the hand-written landing page into dist/.
4. Publish a Markdown twin of every docs page, plus /llms.txt and /llms-full.txt
   (https://llmstxt.org), for agents.

Usage: python3 site/build.py [--rqtk PATH]   (default: builds target/release/rqtk)
Standard library only.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
REPO = SITE.parent
DOCS = SITE / "docs"
SRC = DOCS / "src"
DIST = SITE / "dist"
BASE_URL = "https://rqtk.dev"
GENERATED_NOTE = "<!-- Generated by site/build.py from the rqtk binary; do not edit. -->\n\n"


def run(*args, **kwargs):
    return subprocess.run(args, check=True, capture_output=True, text=True, **kwargs).stdout


# ── reference pages ──────────────────────────────────────────────────────────


def commands_page(rqtk):
    top = run(rqtk, "--help")
    names = []
    in_commands = False
    for line in top.splitlines():
        if line.startswith("Commands:"):
            in_commands = True
            continue
        if in_commands:
            m = re.match(r"^  (\S+)", line)
            if not m:
                break
            if m.group(1) != "help":
                names.append(m.group(1))

    out = [GENERATED_NOTE, "# Commands\n\n",
           "Every command accepts `--json` (one JSON document on stdout) and `--repo-root <DIR>`. ",
           "The same text is available from `rqtk <command> --help`.\n\n",
           "```text\n", top.rstrip(), "\n```\n"]
    for name in names:
        help_text = run(rqtk, name, "--help")
        out += [f"\n## `rqtk {name}`\n\n```text\n", help_text.rstrip(), "\n```\n"]
        sub = re.search(r"^Commands:\n((?:  \S.*\n)+)", help_text, re.M)
        for subname in re.findall(r"^  (\S+)", sub.group(1), re.M) if sub else []:
            if subname == "help":
                continue
            sub_help = run(rqtk, name, subname, "--help")
            out += [f"\n### `rqtk {name} {subname}`\n\n```text\n", sub_help.rstrip(), "\n```\n"]
    return "".join(out)


def lint_rules_page(rqtk):
    rules = json.loads(run(rqtk, "explain", "--json"))
    out = [GENERATED_NOTE, "# Lint rules\n\n",
           "`rqtk lint` reports these findings. Codes are stable: a code keeps its meaning and is ",
           "never reused. `rqtk explain <code>` prints the same information.\n\n",
           "| Code | Severity | Checks | How to fix |\n|---|---|---|---|\n"]
    for r in rules:
        cell = lambda s: s.replace("|", "\\|")
        out.append(f"| <span id=\"{r['code'].lower()}\">{r['code']}</span> | {r['severity']} "
                   f"| {cell(r['summary'])} | {cell(r['fix'])} |\n")
    return "".join(out)


def type_of(schema, defs_seen):
    """A short Markdown description of a JSON Schema's type, linking to $defs."""
    if not isinstance(schema, dict):
        return "any"  # `true` schema
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        defs_seen.add(name)
        return f"[`{name}`](#{name.lower()})"
    if "anyOf" in schema or "oneOf" in schema:
        parts = [type_of(s, defs_seen) for s in schema.get("anyOf", schema.get("oneOf"))]
        return " or ".join(p for p in parts if p != "null") + (" (optional)" if "null" in parts else "")
    t = schema.get("type")
    if isinstance(t, list):
        non_null = [x for x in t if x != "null"]
        base = type_of({**schema, "type": non_null[0]}, defs_seen) if len(non_null) == 1 else " or ".join(non_null)
        return base + (" (optional)" if "null" in t else "")
    if t == "array":
        return f"list of {type_of(schema.get('items', {}), defs_seen)}"
    if t == "object" and "additionalProperties" in schema and isinstance(schema["additionalProperties"], dict):
        return f"table of {type_of(schema['additionalProperties'], defs_seen)}"
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    return f"{t}" if t else "any"


def properties_table(schema, defs_seen):
    props = schema.get("properties", {})
    if not props:
        return "_No fields._\n"
    required = set(schema.get("required", []))
    rows = ["| Field | Type | Required | Description |\n|---|---|---|---|\n"]
    for name, prop in props.items():
        prop = prop if isinstance(prop, dict) else {}
        desc = " ".join(prop.get("description", "").split()).replace("|", "\\|")
        rows.append(f"| `{name}` | {type_of(prop, defs_seen)} | {'yes' if name in required else ''} | {desc} |\n")
    return "".join(rows)


def schema_section(rqtk, kind, heading, level="##"):
    schema = json.loads(run(rqtk, "schema", kind))
    defs = schema.get("$defs", {})
    seen = set()
    out = [f"{level} {heading}\n\n"]
    if schema.get("description"):
        out.append(" ".join(schema["description"].split()) + "\n\n")
    out.append(properties_table(schema, seen))
    done = set()
    while seen - done:
        for name in sorted(seen - done):
            done.add(name)
            d = defs.get(name, {})
            out.append(f"\n{level}# {name}\n\n")
            if d.get("description"):
                out.append(" ".join(d["description"].split()) + "\n\n")
            if "properties" in d:
                out.append(properties_table(d, seen))
            else:
                out.append(f"Type: {type_of(d, seen)}\n")
    return "".join(out)


def file_formats_page(rqtk):
    out = [GENERATED_NOTE, "# File formats\n\n",
           "Every file under `.rqtk/` is TOML and is checked against these fields; unknown fields are ",
           "errors. Dates may be native TOML dates (`2026-03-14`) or strings. ",
           "`rqtk schema <kind>` prints the JSON Schema of each.\n\n"]
    for kind, heading in [("requirement", "Requirement"), ("need", "Need"),
                          ("stakeholder", "Stakeholder"), ("evidence", "Evidence (`.rqtk/evidence.toml`)")]:
        out.append(schema_section(rqtk, kind, heading) + "\n")
    return "".join(out)


def configuration_page(rqtk):
    intro = ("# Configuration\n\n`.rqtk/config.toml` sets the project's vocabulary and policy. "
             "`rqtk init` writes a starting point; `rqtk schema config` prints the JSON Schema.\n\n")
    return GENERATED_NOTE + intro + schema_section(rqtk, "config", "Fields")


# ── site assembly ────────────────────────────────────────────────────────────


def summary_entries():
    """(title, path) for every page in SUMMARY.md, in order."""
    text = (SRC / "SUMMARY.md").read_text()
    return re.findall(r"\[([^\]]+)\]\(([^)]+\.md)\)", text)


def expand_includes(md, base):
    def include(m):
        return (base / m.group(1)).read_text()
    return re.sub(r"\{\{#include ([^}]+)\}\}", include, md)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rqtk", help="rqtk binary to generate the reference from")
    args = parser.parse_args()

    rqtk = args.rqtk
    if not rqtk:
        subprocess.run(["cargo", "build", "--release", "-p", "rqtk"], cwd=REPO, check=True)
        rqtk = str(REPO / "target" / "release" / "rqtk")

    reference = SRC / "reference"
    for name, page in [("commands", commands_page), ("lint-rules", lint_rules_page),
                       ("file-formats", file_formats_page), ("configuration", configuration_page)]:
        (reference / f"{name}.md").write_text(page(rqtk))

    if DIST.exists():
        shutil.rmtree(DIST)
    subprocess.run(["mdbook", "build", str(DOCS)], check=True)

    for item in (SITE / "landing").iterdir():
        shutil.copy(item, DIST / item.name)

    # Markdown twins, llms.txt and llms-full.txt.
    entries = summary_entries()
    index = ["# rqtk\n\n",
             "> Requirements that live in your repository, proven by tests. rqtk keeps requirements, "
             "stakeholder needs and verification evidence as TOML files next to the code, links tests "
             "to requirements, and reports a requirement as verified only when its linked tests passed "
             "against its current wording.\n\n",
             "Every docs page is available as Markdown by replacing `.html` with `.md`.\n\n## Docs\n\n"]
    full = []
    for title, rel in entries:
        page = SRC / rel
        md = expand_includes(page.read_text(), page.parent)
        twin = DIST / "docs" / rel
        twin.parent.mkdir(parents=True, exist_ok=True)
        twin.write_text(md)
        index.append(f"- [{title}]({BASE_URL}/docs/{rel})\n")
        full.append(f"<!-- {BASE_URL}/docs/{rel} -->\n\n{md.strip()}\n")
    (DIST / "llms.txt").write_text("".join(index))
    (DIST / "llms-full.txt").write_text("\n\n---\n\n".join(full) + "\n")

    pages = sum(1 for _ in (DIST / "docs").rglob("*.html"))
    print(f"built {DIST.relative_to(REPO)}: landing page, {pages} docs pages, {len(entries)} Markdown twins")


if __name__ == "__main__":
    sys.exit(main())
