//! Verification evidence: test results matched to verification activities, recorded in
//! `.rqtk/evidence.toml` against the content hash of the requirement they verified.

use crate::error::RqtkError;
use crate::model::{Requirement, RequirementId, SCHEMA_VERSION};
use crate::scan::SourceLink;
use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// Location of the evidence file relative to the repository root.
pub const EVIDENCE_PATH: &str = ".rqtk/evidence.toml";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum Outcome {
    Passed,
    Failed,
}

/// The latest recorded result for one verification activity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActivityEvidence {
    /// Verification activity ID.
    pub id: String,
    /// Requirement that owned the activity when the evidence was recorded.
    pub requirement: RequirementId,
    /// The requirement's content hash when the evidence was recorded. If the requirement's
    /// current hash differs, the evidence is stale and the activity is Suspect.
    pub requirement_hash: String,
    pub outcome: Outcome,
    /// Test cases that produced the outcome, as `classname::name`.
    pub tests: Vec<String>,
    /// Commit checked out when the evidence was recorded.
    pub commit: Option<String>,
}

impl ActivityEvidence {
    /// Equal apart from the commit it was recorded at.
    fn same_result(&self, other: &Self) -> bool {
        self.requirement == other.requirement
            && self.requirement_hash == other.requirement_hash
            && self.outcome == other.outcome
            && self.tests == other.tests
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct EvidenceFile {
    pub schema_version: u32,
    #[serde(default, rename = "activity")]
    pub activities: Vec<ActivityEvidence>,
}

/// All recorded evidence, keyed by activity ID.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Evidence {
    pub activities: BTreeMap<String, ActivityEvidence>,
}

/// How one activity's entry changed when new results were applied.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EvidenceChange {
    Added(ActivityEvidence),
    Updated {
        before: ActivityEvidence,
        after: ActivityEvidence,
    },
    Removed(ActivityEvidence),
}

impl EvidenceChange {
    pub fn activity(&self) -> &str {
        match self {
            EvidenceChange::Added(e) | EvidenceChange::Removed(e) => &e.id,
            EvidenceChange::Updated { after, .. } => &after.id,
        }
    }
}

impl Evidence {
    /// Load `.rqtk/evidence.toml`; a missing file is empty evidence.
    pub fn load(repo_root: &Path) -> Result<Self, RqtkError> {
        let path = repo_root.join(EVIDENCE_PATH);
        let text = match std::fs::read_to_string(&path) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(source) => return Err(RqtkError::Io { path, source }),
        };
        let file: EvidenceFile = toml::from_str(&text).map_err(|source| RqtkError::TomlParse {
            path: path.clone(),
            source,
        })?;
        if file.schema_version != SCHEMA_VERSION {
            return Err(RqtkError::UnsupportedSchemaVersion {
                path,
                found: file.schema_version,
                supported: SCHEMA_VERSION,
            });
        }
        Ok(Self {
            activities: file
                .activities
                .into_iter()
                .map(|e| (e.id.clone(), e))
                .collect(),
        })
    }

    /// Write `.rqtk/evidence.toml`, sorted by activity ID so diffs stay minimal.
    pub fn save(&self, repo_root: &Path) -> Result<(), RqtkError> {
        let path = repo_root.join(EVIDENCE_PATH);
        let file = EvidenceFile {
            schema_version: SCHEMA_VERSION,
            activities: self.activities.values().cloned().collect(),
        };
        let text = format!(
            "# Generated by `rqtk verify`. Commit this file; do not edit by hand.\n{}",
            toml::to_string_pretty(&file)?
        );
        std::fs::write(&path, text).map_err(|source| RqtkError::Io { path, source })
    }

    /// Record the outcomes of a test run. Only activities with a complete result in `runs`
    /// are touched, so partial runs (e.g. one language's tests) keep other evidence. An entry
    /// whose result is unchanged keeps its original commit. Evidence for activities that no
    /// longer exist in any requirement is removed.
    pub fn apply(
        &mut self,
        requirements: &BTreeMap<RequirementId, Requirement>,
        runs: &BTreeMap<String, ActivityRun>,
        commit: Option<&str>,
    ) -> Vec<EvidenceChange> {
        let owners: BTreeMap<&str, &Requirement> = requirements
            .values()
            .flat_map(|r| {
                r.verification
                    .activities
                    .iter()
                    .map(move |a| (a.id.as_str(), r))
            })
            .collect();

        let mut changes = Vec::new();
        for (activity, run) in runs {
            let (Some(req), Some(outcome)) = (owners.get(activity.as_str()), run.outcome()) else {
                continue;
            };
            let entry = ActivityEvidence {
                id: activity.clone(),
                requirement: req.id.clone(),
                requirement_hash: req.compute_content_hash(),
                outcome,
                tests: run.tests.clone(),
                commit: commit.map(str::to_owned),
            };
            match self.activities.get(activity) {
                Some(existing) if existing.same_result(&entry) => {}
                Some(existing) => {
                    changes.push(EvidenceChange::Updated {
                        before: existing.clone(),
                        after: entry.clone(),
                    });
                    self.activities.insert(activity.clone(), entry);
                }
                None => {
                    changes.push(EvidenceChange::Added(entry.clone()));
                    self.activities.insert(activity.clone(), entry);
                }
            }
        }

        let stale: Vec<String> = self
            .activities
            .keys()
            .filter(|id| !owners.contains_key(id.as_str()))
            .cloned()
            .collect();
        for id in stale {
            if let Some(removed) = self.activities.remove(&id) {
                changes.push(EvidenceChange::Removed(removed));
            }
        }
        changes.sort_by(|a, b| a.activity().cmp(b.activity()));
        changes
    }
}

// ── Test results ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TestOutcome {
    Passed,
    Failed,
    Skipped,
}

/// One `<testcase>` from a JUnit XML report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestResult {
    pub name: String,
    pub classname: String,
    pub outcome: TestOutcome,
}

impl TestResult {
    pub fn id(&self) -> String {
        if self.classname.is_empty() {
            self.name.clone()
        } else {
            format!("{}::{}", self.classname, self.name)
        }
    }
}

/// Read test results from a JUnit XML file, as written by cargo-nextest, pytest
/// (`--junitxml`), go-junit-report, jest-junit, Maven Surefire and most CI tools.
pub fn read_junit(path: &Path) -> Result<Vec<TestResult>, RqtkError> {
    let xml = std::fs::read_to_string(path).map_err(|source| RqtkError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    parse_junit(&xml).map_err(|message| RqtkError::TestResults {
        path: PathBuf::from(path),
        message,
    })
}

/// Parse JUnit XML. Several documents may be concatenated, as `cargo test -- --format junit`
/// prints one per test binary.
pub fn parse_junit(xml: &str) -> Result<Vec<TestResult>, String> {
    let mut results = Vec::new();
    for doc in xml.split("<?xml").filter(|d| !d.trim().is_empty()) {
        // Drop the remainder of the XML declaration, if this chunk had one.
        let body = match doc.find("?>") {
            Some(end) if doc.trim_start().starts_with("version") => &doc[end + 2..],
            _ => doc,
        };
        results.extend(parse_junit_document(body)?);
    }
    Ok(results)
}

fn parse_junit_document(xml: &str) -> Result<Vec<TestResult>, String> {
    let mut reader = Reader::from_str(xml);
    let mut results = Vec::new();
    let mut open: Option<TestResult> = None;
    loop {
        match reader.read_event().map_err(|e| e.to_string())? {
            Event::Start(e) if e.local_name().as_ref() == b"testcase" => {
                open = Some(testcase(&e)?);
            }
            Event::Empty(e) if e.local_name().as_ref() == b"testcase" => {
                results.push(testcase(&e)?);
            }
            Event::Start(e) | Event::Empty(e) => {
                if let Some(case) = open.as_mut() {
                    match e.local_name().as_ref() {
                        b"failure" | b"error" => case.outcome = TestOutcome::Failed,
                        b"skipped" if case.outcome == TestOutcome::Passed => {
                            case.outcome = TestOutcome::Skipped;
                        }
                        _ => {}
                    }
                }
            }
            Event::End(e) if e.local_name().as_ref() == b"testcase" => {
                results.extend(open.take());
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(results)
}

fn testcase(e: &BytesStart<'_>) -> Result<TestResult, String> {
    let mut name = None;
    let mut classname = String::new();
    for attr in e.attributes() {
        let attr = attr.map_err(|e| e.to_string())?;
        let value = attr
            .normalized_value(quick_xml::XmlVersion::Implicit1_0)
            .map_err(|e| e.to_string())?;
        match attr.key.local_name().as_ref() {
            b"name" => name = Some(value.into_owned()),
            b"classname" => classname = value.into_owned(),
            _ => {}
        }
    }
    Ok(TestResult {
        name: name.ok_or("<testcase> without a name attribute")?,
        classname,
        outcome: TestOutcome::Passed,
    })
}

// ── Matching results to links ────────────────────────────────────────────────

/// What a test run says about one activity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActivityRun {
    /// IDs of the matched test cases, sorted.
    pub tests: Vec<String>,
    pub any_failed: bool,
    /// Linked test functions with no passing or failing result in the run
    /// (absent, or skipped).
    pub missing: Vec<String>,
}

impl ActivityRun {
    /// `Failed` if any linked test failed; `Passed` only if every linked test ran and passed;
    /// `None` when the run is incomplete for this activity.
    pub fn outcome(&self) -> Option<Outcome> {
        if self.any_failed {
            Some(Outcome::Failed)
        } else if self.missing.is_empty() && !self.tests.is_empty() {
            Some(Outcome::Passed)
        } else {
            None
        }
    }
}

/// Match test results to the activities their test functions are linked to.
/// Activities none of whose tests appear in `results` are left out.
pub fn match_results(
    links: &[SourceLink],
    results: &[TestResult],
) -> BTreeMap<String, ActivityRun> {
    let mut by_activity: BTreeMap<&str, Vec<&SourceLink>> = BTreeMap::new();
    for link in links {
        by_activity.entry(&link.activity).or_default().push(link);
    }

    let mut runs = BTreeMap::new();
    for (activity, links) in by_activity {
        let mut tests = BTreeSet::new();
        let mut any_failed = false;
        let mut missing = Vec::new();
        for link in links {
            let Some(test_name) = &link.test_name else {
                continue;
            };
            let matched = results_for(link, test_name, results);
            let ran: Vec<_> = matched
                .iter()
                .filter(|r| r.outcome != TestOutcome::Skipped)
                .collect();
            if ran.is_empty() {
                missing.push(test_name.clone());
            }
            for r in ran {
                any_failed |= r.outcome == TestOutcome::Failed;
                tests.insert(r.id());
            }
        }
        if tests.is_empty() {
            continue;
        }
        runs.insert(
            activity.to_owned(),
            ActivityRun {
                tests: tests.into_iter().collect(),
                any_failed,
                missing,
            },
        );
    }
    runs
}

/// Results whose name ends with `test_name` at a path boundary. When several match,
/// prefer those whose classname or name mentions the link's file stem.
fn results_for<'a>(
    link: &SourceLink,
    test_name: &str,
    results: &'a [TestResult],
) -> Vec<&'a TestResult> {
    let candidates: Vec<&TestResult> = results
        .iter()
        .filter(|r| name_matches(&r.name, test_name))
        .collect();
    if candidates.len() <= 1 {
        return candidates;
    }
    let stem = link
        .path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_default();
    let narrowed: Vec<&TestResult> = candidates
        .iter()
        .copied()
        .filter(|r| r.classname.contains(stem) || r.name.contains(stem))
        .collect();
    if narrowed.is_empty() {
        candidates
    } else {
        narrowed
    }
}

fn name_matches(result_name: &str, test_name: &str) -> bool {
    // Drop parametrisation suffixes such as pytest's `test_x[case-1]`.
    let name = result_name
        .split_once('[')
        .map_or(result_name, |(head, _)| head)
        .trim_end();
    match name.strip_suffix(test_name) {
        Some("") => true,
        Some(prefix) => prefix.ends_with(['.', ':', ' ', '/', '>']),
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const JUNIT: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="rqtk::integration_test" tests="4">
    <testcase name="lint_ok" classname="rqtk::integration_test" time="0.1"/>
    <testcase name="tests::lint_bad" classname="rqtk::integration_test">
      <failure message="assertion failed">boom &amp; more</failure>
    </testcase>
    <testcase name="later" classname="rqtk::integration_test"><skipped/></testcase>
    <testcase name="test_param[a-1]" classname="tests.test_mod"></testcase>
  </testsuite>
</testsuites>"#;

    fn link(activity: &str, path: &str, test: &str) -> SourceLink {
        SourceLink {
            activity: activity.to_owned(),
            path: PathBuf::from(path),
            line: 1,
            test_name: Some(test.to_owned()),
        }
    }

    #[test]
    fn parses_outcomes() {
        let results = parse_junit(JUNIT).unwrap();
        let outcomes: Vec<_> = results
            .iter()
            .map(|r| (r.name.as_str(), r.outcome))
            .collect();
        assert_eq!(
            outcomes,
            vec![
                ("lint_ok", TestOutcome::Passed),
                ("tests::lint_bad", TestOutcome::Failed),
                ("later", TestOutcome::Skipped),
                ("test_param[a-1]", TestOutcome::Passed),
            ]
        );
    }

    #[test]
    fn parses_concatenated_documents() {
        let one = r#"<?xml version="1.0" encoding="UTF-8"?><testsuites><testsuite name="a"><testcase classname="x" name="t1"/></testsuite></testsuites>"#;
        let two = r#"<?xml version="1.0" encoding="UTF-8"?><testsuites><testsuite name="b"><testcase classname="y" name="t2"><failure/></testcase></testsuite></testsuites>"#;
        let results = parse_junit(&format!("{one}\n{two}\n")).unwrap();
        assert_eq!(results.len(), 2);
        assert_eq!(results[1].outcome, TestOutcome::Failed);
    }

    #[test]
    fn matches_by_name_suffix_and_parametrisation() {
        assert!(name_matches("tests::lint_bad", "lint_bad"));
        assert!(name_matches("test_param[a-1]", "test_param"));
        assert!(name_matches("Suite boots quickly", "boots quickly"));
        assert!(!name_matches("not_lint_bad", "lint_bad"));
    }

    #[test]
    fn activity_outcomes() {
        let results = parse_junit(JUNIT).unwrap();
        let links = [
            link("A", "tests/integration_test.rs", "lint_ok"),
            link("B", "tests/integration_test.rs", "lint_ok"),
            link("B", "tests/integration_test.rs", "lint_bad"),
            link("C", "tests/integration_test.rs", "lint_ok"),
            link("C", "tests/integration_test.rs", "later"),
            link("D", "tests/other.rs", "never_ran"),
        ];
        let runs = match_results(&links, &results);
        assert_eq!(runs["A"].outcome(), Some(Outcome::Passed));
        assert_eq!(runs["A"].tests, vec!["rqtk::integration_test::lint_ok"]);
        assert_eq!(runs["B"].outcome(), Some(Outcome::Failed));
        assert_eq!(
            runs["C"].outcome(),
            None,
            "skipped test leaves C incomplete"
        );
        assert_eq!(runs["C"].missing, vec!["later"]);
        assert!(!runs.contains_key("D"));
    }

    #[test]
    fn prefers_results_from_the_links_file() {
        let results = vec![
            TestResult {
                name: "works".into(),
                classname: "crate::alpha".into(),
                outcome: TestOutcome::Failed,
            },
            TestResult {
                name: "works".into(),
                classname: "crate::beta".into(),
                outcome: TestOutcome::Passed,
            },
        ];
        let runs = match_results(&[link("A", "tests/beta.rs", "works")], &results);
        assert_eq!(runs["A"].outcome(), Some(Outcome::Passed));
    }
}
